repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
        exclude: conda/meta.yaml

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        files: \.[j]sx?|\.css$  # *.js, *.jsx and css
        types: [file]
        exclude: docs/

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v9.25.0
    hooks:
      - id: eslint
        files: \.[j]sx?$  # *.js and *.jsx
        types: [file]
        exclude: docs/
        additional_dependencies:
        - 'eslint@9.25.0'
