import { cn } from "@/lib/utils";

import {
  Tooltip,
  TooltipContent,
  TooltipTrigger,
} from "@/components/ui/tooltip";

import { downloadFile } from "@/utils/downloadUtils";

import DownloadIcon from "../assets/DownloadIcon.svg";

/**
 * Header button that downloads data generated by its parent.
 *
 * @param {Object} props
 * @param {Function} props.onDownload - Called on click; returns
 *   `{ content, filename, mimeType }` describing the file to download.
 * @param {boolean} [props.disabled=false] - Disable the button, e.g. while
 *   data is loading or when there is nothing to download.
 * @param {string} [props.label="Download CSV"] - Tooltip and accessible label.
 */
function DownloadButton({
  onDownload,
  disabled = false,
  label = "Download CSV",
}) {
  const handleClick = () => {
    try {
      const { content, filename, mimeType } = onDownload();
      downloadFile(content, filename, mimeType);
    } catch (err) {
      console.error("Error generating download:", err);
    }
  };

  return (
    <Tooltip>
      <TooltipTrigger asChild>
        <button
          type="button"
          onClick={handleClick}
          disabled={disabled}
          aria-label={label}
          className={cn(
            "min-w-4",
            disabled ? "cursor-not-allowed opacity-50" : "cursor-pointer",
          )}
        >
          <img src={DownloadIcon} alt="Download" />
        </button>
      </TooltipTrigger>
      <TooltipContent>{label}</TooltipContent>
    </Tooltip>
  );
}

export default DownloadButton;
