// Plottable fields with optional plot titles and default bools.
export const PLOT_DEFINITIONS = [
  { key: "s ra", unit: "deg" },
  { key: "s dec", unit: "deg" },
  { key: "sky rotation", unit: "deg" },
  { key: "azimuth start", unit: "deg" },
  { key: "azimuth end", unit: "deg" },
  { key: "azimuth", unit: "deg" },
  { key: "altitude start", unit: "deg" },
  { key: "altitude end", unit: "deg" },
  { key: "altitude", unit: "deg" },
  { key: "zenith distance start", unit: "deg" },
  { key: "zenith distance end", unit: "deg" },
  { key: "zenith distance", unit: "deg" },
  { key: "airmass", title: "Airmass", default: true },
  { key: "exp time", title: "Exposure Time (s)", unit: "sec" },
  { key: "shut time", title: "Shutter Time (s)", unit: "sec" },
  { key: "dark time", title: "Dark Time (s)", unit: "sec" },
  {
    key: "psf median",
    title: "Seeing (PSF FWHM)",
    unit: "arcsec",
    bandMarker: true,
    default: true,
  },
  {
    key: "zero point median",
    title: "Photometric Zero Points",
    unit: "magnitude",
    bandMarker: true,
    showMoon: true,
    default: true,
  },
  { key: "air temp", title: "Air Temperature (°C)", unit: "°C" },
  {
    key: "mt salindex112 temperature 0 mean",
    title: "Mean Dome Temperature at M2 (°C)",
    unit: "°C",
  },
  { key: "pressure", unit: "Pa" },
  { key: "humidity", unit: "%" },
  { key: "wind speed", unit: "m/s" },
  { key: "wind dir", title: "Wind Direction", unit: "deg" },
  { key: "focus z" },
  { key: "n inputs", unit: "count" },
  { key: "pixel scale min", unit: "arcsec/pixel" },
  { key: "pixel scale max", unit: "arcsec/pixel" },
  { key: "pixel scale median", unit: "arcsec/pixel" },
  { key: "astrom offset mean min", unit: "arcsec" },
  { key: "astrom offset mean max", unit: "arcsec" },
  { key: "astrom offset mean median", unit: "arcsec" },
  { key: "astrom offset std min", unit: "arcsec" },
  { key: "astrom offset std max", unit: "arcsec" },
  { key: "astrom offset std median", unit: "arcsec" },
  { key: "eff time min", unit: "s" },
  { key: "eff time max", unit: "s" },
  { key: "eff time median", unit: "s" },
  { key: "eff time psf sigma scale min", bandMarker: true },
  { key: "eff time psf sigma scale max", bandMarker: true },
  { key: "eff time psf sigma scale median", bandMarker: true },
  { key: "eff time sky bg scale min", showMoon: true },
  { key: "eff time sky bg scale max", showMoon: true },
  { key: "eff time sky bg scale median", showMoon: true },
  { key: "eff time zero point scale min", bandMarker: true, showMoon: true },
  { key: "eff time zero point scale max", bandMarker: true, showMoon: true },
  { key: "eff time zero point scale median", bandMarker: true, showMoon: true },
  { key: "stats mag lim min", unit: "magnitude" },
  { key: "stats mag lim max", unit: "magnitude" },
  { key: "stats mag lim median", unit: "magnitude" },
  { key: "psf ap flux delta min", bandMarker: true },
  { key: "psf ap flux delta max", bandMarker: true },
  { key: "psf ap flux delta median", bandMarker: true },
  { key: "psf ap corr sigma scaled delta min", bandMarker: true },
  { key: "psf ap corr sigma scaled delta max", bandMarker: true },
  { key: "psf ap corr sigma scaled delta median", bandMarker: true },
  { key: "max dist to nearest psf min", unit: "pixel", bandMarker: true },
  { key: "max dist to nearest psf max", unit: "pixel", bandMarker: true },
  { key: "max dist to nearest psf median", unit: "pixel", bandMarker: true },
  { key: "mean var min", unit: "count²" },
  { key: "mean var max", unit: "count²" },
  { key: "mean var median", unit: "count²" },
  { key: "n psf star min", unit: "count", bandMarker: true },
  { key: "n psf star max", unit: "count", bandMarker: true },
  { key: "n psf star median", unit: "count", bandMarker: true },
  { key: "n psf star total", unit: "count", bandMarker: true },
  { key: "psf area min", unit: "pixel²", bandMarker: true },
  { key: "psf area max", unit: "pixel²", bandMarker: true },
  { key: "psf area median", unit: "pixel²", bandMarker: true },
  { key: "psf ixx min", unit: "pixel²", bandMarker: true },
  { key: "psf ixx max", unit: "pixel²", bandMarker: true },
  { key: "psf ixx median", unit: "pixel²", bandMarker: true },
  { key: "psf ixy min", unit: "pixel²", bandMarker: true },
  { key: "psf ixy max", unit: "pixel²", bandMarker: true },
  { key: "psf ixy median", unit: "pixel²", bandMarker: true },
  { key: "psf iyy min", unit: "pixel²", bandMarker: true },
  { key: "psf iyy max", unit: "pixel²", bandMarker: true },
  { key: "psf iyy median", unit: "pixel²", bandMarker: true },
  { key: "psf sigma min", unit: "pixel", bandMarker: true },
  { key: "psf sigma max", unit: "pixel", bandMarker: true },
  { key: "psf sigma median", unit: "pixel", bandMarker: true },
  { key: "psf star delta e1 median min", bandMarker: true },
  { key: "psf star delta e1 median max", bandMarker: true },
  { key: "psf star delta e1 median median", bandMarker: true },
  { key: "psf star delta e1 scatter min", bandMarker: true },
  { key: "psf star delta e1 scatter max", bandMarker: true },
  { key: "psf star delta e1 scatter median", bandMarker: true },
  { key: "psf star delta e2 median min", bandMarker: true },
  { key: "psf star delta e2 median max", bandMarker: true },
  { key: "psf star delta e2 median median", bandMarker: true },
  { key: "psf star delta e2 scatter min", bandMarker: true },
  { key: "psf star delta e2 scatter max", bandMarker: true },
  { key: "psf star delta e2 scatter median", bandMarker: true },
  { key: "psf star delta size median min", unit: "pixel", bandMarker: true },
  { key: "psf star delta size median max", unit: "pixel", bandMarker: true },
  { key: "psf star delta size median median", unit: "pixel", bandMarker: true },
  { key: "psf star delta size scatter min", unit: "pixel", bandMarker: true },
  { key: "psf star delta size scatter max", unit: "pixel", bandMarker: true },
  {
    key: "psf star delta size scatter median",
    unit: "pixel",
    bandMarker: true,
  },
  { key: "psf star scaled delta size scatter min", bandMarker: true },
  { key: "psf star scaled delta size scatter max", bandMarker: true },
  { key: "psf star scaled delta size scatter median", bandMarker: true },
  { key: "psf trace radius delta min", unit: "pixel", bandMarker: true },
  { key: "psf trace radius delta max", unit: "pixel", bandMarker: true },
  { key: "psf trace radius delta median", unit: "pixel", bandMarker: true },
  { key: "sky bg min", unit: "count", bandMarker: true, showMoon: true },
  { key: "sky bg max", unit: "count", bandMarker: true, showMoon: true },
  {
    key: "sky bg median",
    unit: "count",
    title: "Sky Brightness",
    bandMarker: true,
    showMoon: true,
    default: true,
  },
  { key: "sky noise min", unit: "count", bandMarker: true, showMoon: true },
  { key: "sky noise max", unit: "count", bandMarker: true, showMoon: true },
  { key: "sky noise median", unit: "count", bandMarker: true, showMoon: true },
  {
    key: "zero point min",
    unit: "magnitude",
    bandMarker: true,
    showMoon: true,
  },
  {
    key: "zero point max",
    unit: "magnitude",
    bandMarker: true,
    showMoon: true,
  },
  { key: "low snr source count min", unit: "count" },
  { key: "low snr source count max", unit: "count" },
  { key: "low snr source count median", unit: "count" },
  { key: "low snr source count total", unit: "count" },
  { key: "high snr source count min", unit: "count" },
  { key: "high snr source count max", unit: "count" },
  { key: "high snr source count median", unit: "count" },
  { key: "high snr source count total", unit: "count" },
  { key: "ringss seeing", unit: "arcsec" },
  { key: "aos fwhm", unit: "arcsec" },
  { key: "donut blur fwhm", unit: "arcsec" },
  { key: "physical rotator angle", unit: "degree" },
  { key: "dimm seeing", unit: "arcsec", title: "DIMM Seeing" },
];

export const PLOT_COLOR_OPTIONS = [
  { key: "assorted", label: "Assorted" },
  { key: "white", label: "White", color: "#FFFFFF" },
  { key: "green", label: "Green", color: "#3CAE3F" },
  { key: "turquoise", label: "Turquoise", color: "#00BABC" },
  { key: "blue", label: "Blue", color: "#2A6FF2" },
  { key: "purple", label: "Purple", color: "#8E44AD" },
  { key: "pink", label: "Pink", color: "#FF3CAC" },
  { key: "red", label: "Red", color: "#E63946" },
  { key: "orange", label: "Orange", color: "#FF7F11" },
  { key: "yellow", label: "Yellow", color: "#FFD60A" },
];

export const PLOT_DOT_OPTIONS = [
  { key: "line", label: "Lines" },
  { key: "dots", label: "Dots" },
];

export const PLOT_KEY_TIME = "time";
export const PLOT_KEY_SEQUENCE = "seq";

export const PLOT_X_AXIS_OPTIONS = [
  { key: PLOT_KEY_TIME, label: "Time" },
  { key: PLOT_KEY_SEQUENCE, label: "Sequence Number" },
];

export const PLOT_BAND_MARKER_OPTIONS = [
  { key: "none", label: "None" },
  { key: "bandColor", label: "Colors" },
  { key: "bandColorsIcons", label: "Colors & Icons" },
];

export const BAND_COLORS = {
  u: "#3eb7ff",
  g: "#30c39f",
  r: "#ff7e00",
  i: "#2af5ff",
  z: "#a7f9c1",
  y: "#fdc900",
};

// Plot styling constants
export const PLOT_COLORS = {
  gridStroke: "#555",
  moonFill: "#EAB308",
  twilightStroke: "#0ea5e9",
  noDataFill: "#ccc",
  defaultColor: "#ffffff",
  activeDotFill: "#ffffff",
};

export const PLOT_DIMENSIONS = {
  activeDotRadius: 4,
  yAxisWidth: 70,
  axisLabelFontSize: 16,
  axisLabelFontWeight: 100,
  axisLabelFill: "white",
  chartMargins: { top: 10, right: 0, left: 5, bottom: 24 },
};

export const PLOT_OPACITIES = {
  overlay: 0.2,
  selection: 0.3,
};

export const AXIS_TICK_STYLE = {
  fill: "white",
  style: { userSelect: "none" },
};
