// Plottable fields with optional plot titles and default bools.
export const PLOT_DEFINITIONS = [
  { key: "s ra" },
  { key: "s dec" },
  { key: "sky rotation" },
  { key: "azimuth start" },
  { key: "azimuth end" },
  { key: "azimuth" },
  { key: "altitude start" },
  { key: "altitude end" },
  { key: "altitude" },
  { key: "zenith distance start" },
  { key: "zenith distance end" },
  { key: "zenith distance" },
  { key: "airmass", title: "Airmass", default: true },
  { key: "exp time", title: "Exposure Time (s)" },
  { key: "shut time", title: "Shutter Time (s)" },
  { key: "dark time", title: "Dark Time (s)" },
  {
    key: "psf median",
    title: "Seeing (PSF FWHM)",
    unit: "arcsec",
    bandMarker: true,
    default: true,
  },
  {
    key: "zero point median",
    title: "Photometric Zero Points",
    unit: "magnitude",
    bandMarker: true,
    default: true,
  },
  { key: "air temp", title: "Air Temperature (°C)" },
  { key: "pressure" },
  { key: "humidity" },
  { key: "wind speed" },
  { key: "wind dir" },
  { key: "focus z" },
  { key: "n inputs" },
  { key: "pixel scale min" },
  { key: "pixel scale max" },
  { key: "pixel scale median" },
  { key: "astrom offset mean min" },
  { key: "astrom offset mean max" },
  { key: "astrom offset mean median" },
  { key: "astrom offset std min" },
  { key: "astrom offset std max" },
  { key: "astrom offset std median" },
  { key: "eff time min" },
  { key: "eff time max" },
  { key: "eff time median" },
  { key: "eff time psf sigma scale min", bandMarker: true },
  { key: "eff time psf sigma scale max", bandMarker: true },
  { key: "eff time psf sigma scale median", bandMarker: true },
  { key: "eff time sky bg scale min" },
  { key: "eff time sky bg scale max" },
  { key: "eff time sky bg scale median" },
  { key: "eff time zero point scale min", bandMarker: true },
  { key: "eff time zero point scale max", bandMarker: true },
  { key: "eff time zero point scale median", bandMarker: true },
  { key: "stats mag lim min" },
  { key: "stats mag lim max" },
  { key: "stats mag lim median" },
  { key: "psf ap flux delta min", bandMarker: true },
  { key: "psf ap flux delta max", bandMarker: true },
  { key: "psf ap flux delta median", bandMarker: true },
  { key: "psf ap corr sigma scaled delta min", bandMarker: true },
  { key: "psf ap corr sigma scaled delta max", bandMarker: true },
  { key: "psf ap corr sigma scaled delta median", bandMarker: true },
  { key: "max dist to nearest psf min", bandMarker: true },
  { key: "max dist to nearest psf max", bandMarker: true },
  { key: "max dist to nearest psf median", bandMarker: true },
  { key: "mean var min" },
  { key: "mean var max" },
  { key: "mean var median" },
  { key: "n psf star min", bandMarker: true },
  { key: "n psf star max", bandMarker: true },
  { key: "n psf star median", bandMarker: true },
  { key: "n psf star total", bandMarker: true },
  { key: "psf area min", bandMarker: true },
  { key: "psf area max", bandMarker: true },
  { key: "psf area median", bandMarker: true },
  { key: "psf ixx min", bandMarker: true },
  { key: "psf ixx max", bandMarker: true },
  { key: "psf ixx median", bandMarker: true },
  { key: "psf ixy min", bandMarker: true },
  { key: "psf ixy max", bandMarker: true },
  { key: "psf ixy median", bandMarker: true },
  { key: "psf iyy min", bandMarker: true },
  { key: "psf iyy max", bandMarker: true },
  { key: "psf iyy median", bandMarker: true },
  { key: "psf sigma min", bandMarker: true },
  { key: "psf sigma max", bandMarker: true },
  { key: "psf sigma median", bandMarker: true },
  { key: "psf star delta e1 median min", bandMarker: true },
  { key: "psf star delta e1 median max", bandMarker: true },
  { key: "psf star delta e1 median median", bandMarker: true },
  { key: "psf star delta e1 scatter min", bandMarker: true },
  { key: "psf star delta e1 scatter max", bandMarker: true },
  { key: "psf star delta e1 scatter median", bandMarker: true },
  { key: "psf star delta e2 median min", bandMarker: true },
  { key: "psf star delta e2 median max", bandMarker: true },
  { key: "psf star delta e2 median median", bandMarker: true },
  { key: "psf star delta e2 scatter min", bandMarker: true },
  { key: "psf star delta e2 scatter max", bandMarker: true },
  { key: "psf star delta e2 scatter median", bandMarker: true },
  { key: "psf star delta size median min", bandMarker: true },
  { key: "psf star delta size median max", bandMarker: true },
  { key: "psf star delta size median median", bandMarker: true },
  { key: "psf star delta size scatter min", bandMarker: true },
  { key: "psf star delta size scatter max", bandMarker: true },
  { key: "psf star delta size scatter median", bandMarker: true },
  { key: "psf star scaled delta size scatter min", bandMarker: true },
  { key: "psf star scaled delta size scatter max", bandMarker: true },
  { key: "psf star scaled delta size scatter median", bandMarker: true },
  { key: "psf trace radius delta min", bandMarker: true },
  { key: "psf trace radius delta max", bandMarker: true },
  { key: "psf trace radius delta median", bandMarker: true },
  { key: "sky bg min" },
  { key: "sky bg max" },
  { key: "sky bg median", title: "Sky Brightness", default: true },
  { key: "sky noise min" },
  { key: "sky noise max" },
  { key: "sky noise median" },
  { key: "zero point min", bandMarker: true },
  { key: "zero point max", bandMarker: true },
];

export const PLOT_COLOR_OPTIONS = [
  { key: "assorted", label: "Assorted" },
  { key: "white", label: "White", color: "#FFFFFF" },
  { key: "green", label: "Green", color: "#3CAE3F" },
  { key: "turquoise", label: "Turquoise", color: "#00BABC" },
  { key: "blue", label: "Blue", color: "#2A6FF2" },
  { key: "purple", label: "Purple", color: "#8E44AD" },
  { key: "pink", label: "Pink", color: "#FF3CAC" },
  { key: "red", label: "Red", color: "#E63946" },
  { key: "orange", label: "Orange", color: "#FF7F11" },
  { key: "yellow", label: "Yellow", color: "#FFD60A" },
];

export const PLOT_DOT_OPTIONS = [
  { key: "line", label: "Lines" },
  { key: "dots", label: "Dots" },
];

export const PLOT_BAND_MARKER_OPTIONS = [
  { key: "none", label: "None" },
  { key: "bandColor", label: "Colors" },
  { key: "bandColorsIcons", label: "Colors & Icons" },
];

// TODO: import these in plotDotShapes
export const BAND_COLOURS = {
  u: { color: "#3eb7ff" },
  g: { color: "#30c39f" },
  r: { color: "#ff7e00" },
  i: { color: "#2af5ff" },
  z: { color: "#a7f9c1" },
  y: { color: "#fdc900" },
};

export const BAND_COLORS = {
  u: "#3eb7ff",
  g: "#30c39f",
  r: "#ff7e00",
  i: "#2af5ff",
  z: "#a7f9c1",
  y: "#fdc900",
};
