// Plottable fields with optional plot titles and default bools.
export const PLOT_DEFINITIONS = [
  { key: "s_ra", unit: "deg" },
  { key: "s_dec", unit: "deg" },
  { key: "sky_rotation", unit: "deg" },
  { key: "azimuth_start", unit: "deg" },
  { key: "azimuth_end", unit: "deg" },
  { key: "azimuth", unit: "deg" },
  { key: "altitude_start", unit: "deg" },
  { key: "altitude_end", unit: "deg" },
  { key: "altitude", unit: "deg" },
  { key: "zenith_distance_start", unit: "deg" },
  { key: "zenith_distance_end", unit: "deg" },
  { key: "zenith_distance", unit: "deg" },
  { key: "airmass", title: "Airmass", default: true },
  { key: "exp_time", title: "Exposure Time (s)", unit: "sec" },
  { key: "shut_time", title: "Shutter Time (s)", unit: "sec" },
  { key: "dark_time", title: "Dark Time (s)", unit: "sec" },
  {
    key: "psf_median",
    title: "Seeing (PSF FWHM)",
    unit: "arcsec",
    bandMarker: true,
    default: true,
  },
  {
    key: "zero_point_median",
    title: "Photometric Zero Points",
    unit: "magnitude",
    bandMarker: true,
    showMoon: true,
    default: true,
  },
  { key: "air_temp", title: "Air Temperature (°C)", unit: "°C" },
  {
    key: "mt_salindex112_temperature_0_mean",
    title: "Mean Dome Temperature at M2 (°C)",
    unit: "°C",
  },
  { key: "pressure", unit: "Pa" },
  { key: "humidity", unit: "%" },
  { key: "wind_speed", unit: "m/s" },
  { key: "wind_dir", title: "Wind Direction", unit: "deg" },
  { key: "focus_z" },
  { key: "n_inputs", unit: "count" },
  { key: "pixel_scale_min", unit: "arcsec/pixel" },
  { key: "pixel_scale_max", unit: "arcsec/pixel" },
  { key: "pixel_scale_median", unit: "arcsec/pixel" },
  { key: "astrom_offset_mean_min", unit: "arcsec" },
  { key: "astrom_offset_mean_max", unit: "arcsec" },
  { key: "astrom_offset_mean_median", unit: "arcsec" },
  { key: "astrom_offset_std_min", unit: "arcsec" },
  { key: "astrom_offset_std_max", unit: "arcsec" },
  { key: "astrom_offset_std_median", unit: "arcsec" },
  { key: "eff_time_min", unit: "s" },
  { key: "eff_time_max", unit: "s" },
  { key: "eff_time_median", unit: "s" },
  { key: "eff_time_psf_sigma_scale_min", bandMarker: true },
  { key: "eff_time_psf_sigma_scale_max", bandMarker: true },
  { key: "eff_time_psf_sigma_scale_median", bandMarker: true },
  { key: "eff_time_sky_bg_scale_min", showMoon: true },
  { key: "eff_time_sky_bg_scale_max", showMoon: true },
  { key: "eff_time_sky_bg_scale_median", showMoon: true },
  { key: "eff_time_zero_point_scale_min", bandMarker: true, showMoon: true },
  { key: "eff_time_zero_point_scale_max", bandMarker: true, showMoon: true },
  { key: "eff_time_zero_point_scale_median", bandMarker: true, showMoon: true },
  { key: "stats_mag_lim_min", unit: "magnitude" },
  { key: "stats_mag_lim_max", unit: "magnitude" },
  { key: "stats_mag_lim_median", unit: "magnitude" },
  { key: "psf_ap_flux_delta_min", bandMarker: true },
  { key: "psf_ap_flux_delta_max", bandMarker: true },
  { key: "psf_ap_flux_delta_median", bandMarker: true },
  { key: "psf_ap_corr_sigma_scaled_delta_min", bandMarker: true },
  { key: "psf_ap_corr_sigma_scaled_delta_max", bandMarker: true },
  { key: "psf_ap_corr_sigma_scaled_delta_median", bandMarker: true },
  { key: "max_dist_to_nearest_psf_min", unit: "pixel", bandMarker: true },
  { key: "max_dist_to_nearest_psf_max", unit: "pixel", bandMarker: true },
  { key: "max_dist_to_nearest_psf_median", unit: "pixel", bandMarker: true },
  { key: "mean_var_min", unit: "count²" },
  { key: "mean_var_max", unit: "count²" },
  { key: "mean_var_median", unit: "count²" },
  { key: "n_psf_star_min", unit: "count", bandMarker: true },
  { key: "n_psf_star_max", unit: "count", bandMarker: true },
  { key: "n_psf_star_median", unit: "count", bandMarker: true },
  { key: "n_psf_star_total", unit: "count", bandMarker: true },
  { key: "psf_area_min", unit: "pixel²", bandMarker: true },
  { key: "psf_area_max", unit: "pixel²", bandMarker: true },
  { key: "psf_area_median", unit: "pixel²", bandMarker: true },
  { key: "psf_ixx_min", unit: "pixel²", bandMarker: true },
  { key: "psf_ixx_max", unit: "pixel²", bandMarker: true },
  { key: "psf_ixx_median", unit: "pixel²", bandMarker: true },
  { key: "psf_ixy_min", unit: "pixel²", bandMarker: true },
  { key: "psf_ixy_max", unit: "pixel²", bandMarker: true },
  { key: "psf_ixy_median", unit: "pixel²", bandMarker: true },
  { key: "psf_iyy_min", unit: "pixel²", bandMarker: true },
  { key: "psf_iyy_max", unit: "pixel²", bandMarker: true },
  { key: "psf_iyy_median", unit: "pixel²", bandMarker: true },
  { key: "psf_sigma_min", unit: "pixel", bandMarker: true },
  { key: "psf_sigma_max", unit: "pixel", bandMarker: true },
  { key: "psf_sigma_median", unit: "pixel", bandMarker: true },
  { key: "psf_star_delta_e1_median_min", bandMarker: true },
  { key: "psf_star_delta_e1_median_max", bandMarker: true },
  { key: "psf_star_delta_e1_median_median", bandMarker: true },
  { key: "psf_star_delta_e1_scatter_min", bandMarker: true },
  { key: "psf_star_delta_e1_scatter_max", bandMarker: true },
  { key: "psf_star_delta_e1_scatter_median", bandMarker: true },
  { key: "psf_star_delta_e2_median_min", bandMarker: true },
  { key: "psf_star_delta_e2_median_max", bandMarker: true },
  { key: "psf_star_delta_e2_median_median", bandMarker: true },
  { key: "psf_star_delta_e2_scatter_min", bandMarker: true },
  { key: "psf_star_delta_e2_scatter_max", bandMarker: true },
  { key: "psf_star_delta_e2_scatter_median", bandMarker: true },
  { key: "psf_star_delta_size_median_min", unit: "pixel", bandMarker: true },
  { key: "psf_star_delta_size_median_max", unit: "pixel", bandMarker: true },
  { key: "psf_star_delta_size_median_median", unit: "pixel", bandMarker: true },
  { key: "psf_star_delta_size_scatter_min", unit: "pixel", bandMarker: true },
  { key: "psf_star_delta_size_scatter_max", unit: "pixel", bandMarker: true },
  {
    key: "psf_star_delta_size_scatter_median",
    unit: "pixel",
    bandMarker: true,
  },
  { key: "psf_star_scaled_delta_size_scatter_min", bandMarker: true },
  { key: "psf_star_scaled_delta_size_scatter_max", bandMarker: true },
  { key: "psf_star_scaled_delta_size_scatter_median", bandMarker: true },
  { key: "psf_trace_radius_delta_min", unit: "pixel", bandMarker: true },
  { key: "psf_trace_radius_delta_max", unit: "pixel", bandMarker: true },
  { key: "psf_trace_radius_delta_median", unit: "pixel", bandMarker: true },
  { key: "sky_bg_min", unit: "count", bandMarker: true, showMoon: true },
  { key: "sky_bg_max", unit: "count", bandMarker: true, showMoon: true },
  {
    key: "sky_bg_median",
    unit: "count",
    title: "Sky Brightness",
    bandMarker: true,
    showMoon: true,
    default: true,
  },
  { key: "sky_noise_min", unit: "count", bandMarker: true, showMoon: true },
  { key: "sky_noise_max", unit: "count", bandMarker: true, showMoon: true },
  { key: "sky_noise_median", unit: "count", bandMarker: true, showMoon: true },
  {
    key: "zero_point_min",
    unit: "magnitude",
    bandMarker: true,
    showMoon: true,
  },
  {
    key: "zero_point_max",
    unit: "magnitude",
    bandMarker: true,
    showMoon: true,
  },
  { key: "low_snr_source_count_min", unit: "count" },
  { key: "low_snr_source_count_max", unit: "count" },
  { key: "low_snr_source_count_median", unit: "count" },
  { key: "low_snr_source_count_total", unit: "count" },
  { key: "high_snr_source_count_min", unit: "count" },
  { key: "high_snr_source_count_max", unit: "count" },
  { key: "high_snr_source_count_median", unit: "count" },
  { key: "high_snr_source_count_total", unit: "count" },
  { key: "ringss_seeing", unit: "arcsec" },
  { key: "aos_fwhm", unit: "arcsec" },
  { key: "donut_blur_fwhm", unit: "arcsec" },
  { key: "physical_rotator_angle", unit: "degree" },
  { key: "dimm_seeing", unit: "arcsec", title: "DIMM Seeing" },
];

export const PLOT_COLOR_OPTIONS = [
  { key: "assorted", label: "Assorted" },
  { key: "white", label: "White", color: "#FFFFFF" },
  { key: "green", label: "Green", color: "#3CAE3F" },
  { key: "turquoise", label: "Turquoise", color: "#00BABC" },
  { key: "blue", label: "Blue", color: "#2A6FF2" },
  { key: "purple", label: "Purple", color: "#8E44AD" },
  { key: "pink", label: "Pink", color: "#FF3CAC" },
  { key: "red", label: "Red", color: "#E63946" },
  { key: "orange", label: "Orange", color: "#FF7F11" },
  { key: "yellow", label: "Yellow", color: "#FFD60A" },
];

export const PLOT_DOT_OPTIONS = [
  { key: "line", label: "Lines" },
  { key: "dots", label: "Dots" },
];

export const PLOT_KEY_TIME = "time";
export const PLOT_KEY_SEQUENCE = "seq";

export const PLOT_X_AXIS_OPTIONS = [
  { key: PLOT_KEY_TIME, label: "Time" },
  { key: PLOT_KEY_SEQUENCE, label: "Sequence Number" },
];

export const PLOT_BAND_MARKER_OPTIONS = [
  { key: "none", label: "None" },
  { key: "bandColor", label: "Colors" },
  { key: "bandColorsIcons", label: "Colors & Icons" },
];

export const BAND_COLORS = {
  u: "#3eb7ff",
  g: "#30c39f",
  r: "#ff7e00",
  i: "#2af5ff",
  z: "#a7f9c1",
  y: "#fdc900",
};

// Plot styling constants
export const PLOT_COLORS = {
  gridStroke: "#555",
  moonFill: "#EAB308",
  twilightStroke: "#0ea5e9",
  noDataFill: "#ccc",
  defaultColor: "#ffffff",
  hoveredDotFill: "#ffffff",
};

export const PLOT_DIMENSIONS = {
  hoveredDotRadius: 5,
  yAxisWidth: 70,
  axisLabelFontSize: 16,
  axisLabelFontWeight: 100,
  axisLabelFill: "white",
  chartMargins: { top: 10, right: 0, left: 5, bottom: 24 },
};

export const PLOT_OPACITIES = {
  overlay: 0.2,
  selection: 0.3,
};

export const AXIS_TICK_STYLE = {
  fill: "white",
  style: { userSelect: "none" },
};

export const DAYOBS_AXIS_TICK_STYLE = {
  fill: "grey",
  style: { userSelect: "none" },
};
