// Plottable fields with optional plot titles and default bools.
export const PLOT_DEFINITIONS = [
  { key: "s ra" },
  { key: "s dec" },
  { key: "sky rotation" },
  { key: "azimuth start" },
  { key: "azimuth end" },
  { key: "azimuth" },
  { key: "altitude start" },
  { key: "altitude end" },
  { key: "altitude" },
  { key: "zenith distance start" },
  { key: "zenith distance end" },
  { key: "zenith distance" },
  { key: "airmass", title: "Airmass", default: true },
  { key: "exp time", title: "Exposure Time (s)" },
  { key: "shut time", title: "Shutter Time (s)" },
  { key: "dark time", title: "Dark Time (s)" },
  {
    key: "psf median",
    title: "Seeing (PSF FWHM)",
    unit: "arcsec",
    default: true,
  },
  {
    key: "zero point median",
    title: "Photometric Zero Points",
    unit: "magnitude",
    default: true,
  },
  { key: "air temp", title: "Air Temperature (°C)" },
  { key: "pressure" },
  { key: "humidity" },
  { key: "wind speed" },
  { key: "wind dir" },
  { key: "focus z" },
  { key: "n inputs" },
  { key: "pixel scale min" },
  { key: "pixel scale max" },
  { key: "pixel scale median" },
  { key: "astrom offset mean min" },
  { key: "astrom offset mean max" },
  { key: "astrom offset mean median" },
  { key: "astrom offset std min" },
  { key: "astrom offset std max" },
  { key: "astrom offset std median" },
  { key: "eff time min" },
  { key: "eff time max" },
  { key: "eff time median" },
  { key: "eff time psf sigma scale min" },
  { key: "eff time psf sigma scale max" },
  { key: "eff time psf sigma scale median" },
  { key: "eff time sky bg scale min" },
  { key: "eff time sky bg scale max" },
  { key: "eff time sky bg scale median" },
  { key: "eff time zero point scale min" },
  { key: "eff time zero point scale max" },
  { key: "eff time zero point scale median" },
  { key: "stats mag lim min" },
  { key: "stats mag lim max" },
  { key: "stats mag lim median" },
  { key: "psf ap flux delta min" },
  { key: "psf ap flux delta max" },
  { key: "psf ap flux delta median" },
  { key: "psf ap corr sigma scaled delta min" },
  { key: "psf ap corr sigma scaled delta max" },
  { key: "psf ap corr sigma scaled delta median" },
  { key: "max dist to nearest psf min" },
  { key: "max dist to nearest psf max" },
  { key: "max dist to nearest psf median" },
  { key: "mean var min" },
  { key: "mean var max" },
  { key: "mean var median" },
  { key: "n psf star min" },
  { key: "n psf star max" },
  { key: "n psf star median" },
  { key: "n psf star total" },
  { key: "psf area min" },
  { key: "psf area max" },
  { key: "psf area median" },
  { key: "psf ixx min" },
  { key: "psf ixx max" },
  { key: "psf ixx median" },
  { key: "psf ixy min" },
  { key: "psf ixy max" },
  { key: "psf ixy median" },
  { key: "psf iyy min" },
  { key: "psf iyy max" },
  { key: "psf iyy median" },
  { key: "psf sigma min" },
  { key: "psf sigma max" },
  { key: "psf sigma median" },
  { key: "psf star delta e1 median min" },
  { key: "psf star delta e1 median max" },
  { key: "psf star delta e1 median median" },
  { key: "psf star delta e1 scatter min" },
  { key: "psf star delta e1 scatter max" },
  { key: "psf star delta e1 scatter median" },
  { key: "psf star delta e2 median min" },
  { key: "psf star delta e2 median max" },
  { key: "psf star delta e2 median median" },
  { key: "psf star delta e2 scatter min" },
  { key: "psf star delta e2 scatter max" },
  { key: "psf star delta e2 scatter median" },
  { key: "psf star delta size median min" },
  { key: "psf star delta size median max" },
  { key: "psf star delta size median median" },
  { key: "psf star delta size scatter min" },
  { key: "psf star delta size scatter max" },
  { key: "psf star delta size scatter median" },
  { key: "psf star scaled delta size scatter min" },
  { key: "psf star scaled delta size scatter max" },
  { key: "psf star scaled delta size scatter median" },
  { key: "psf trace radius delta min" },
  { key: "psf trace radius delta max" },
  { key: "psf trace radius delta median" },
  { key: "sky bg min" },
  { key: "sky bg max" },
  { key: "sky bg median", title: "Sky Brightness", default: true },
  { key: "sky noise min" },
  { key: "sky noise max" },
  { key: "sky noise median" },
  { key: "zero point min" },
  { key: "zero point max" },
];
